### ISSUE TITLE
How to use it for elliptic curve?

### ISSUE THREAD

**Issue by ghost** [mhinkie/ShorDiscreteLog#1]
How can I use it for the curve below?

![Screenshot at 2023-01-18 10-58-45](https://user-images.githubusercontent.com/71072847/213111198-4464dc57-2a87-4086-aea4-3216c45e3849.png)

**Comment by mhinkie** [comment]
Hello,

In this repository, only the oracle for multiplication modulo a prime is implemented. To use this implementation for elliptic curves, the oracle for the group operation needs to be implemented. One way how this can be achieved is described in 

Proos, John, and Christof Zalka. "Shor's discrete logarithm quantum algorithm for elliptic curves." arXiv preprint quant-ph/0301141 (2003). (https://arxiv.org/abs/quant-ph/0301141)

However, I'm not sure how feasible an implementation of this operator is since it requires the euclidean algorithm that uses relatively many qubits. Especially if it should be executed on quantum simulators this might not be feasible.
